sudo: false
language: node_js
cache:
  yarn: true
notifications:
  email: false
node_js:
  - '10'
install:
  - yarn
script:
  - yarn run lint
  - yarn run flow
  - yarn run jest
after_success:
  - semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
